-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 16:07:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema centrosacad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema centrosacad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centrosacad` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `centrosacad` ;

-- -----------------------------------------------------
-- Table `centrosacad`.`tbUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbUsuarios` (
  `nombreUsuario` VARCHAR(8) NOT NULL COMMENT 'Nombre de usuario con el que acceder a la aplicación',
  `password` VARCHAR(100) NOT NULL,
  `nivelAcceso` INT NOT NULL,
  `nombreCompleto` VARCHAR(50) NOT NULL,
  `codCentro` INT NOT NULL,
  `activo` TINYINT(1) NULL,
  `idProfesor` VARCHAR(6) NULL,
  PRIMARY KEY (`nombreUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci
COMMENT = 'Tabla que almacena los datos de acceso de los usuarios';


-- -----------------------------------------------------
-- Table `centrosacad`.`tbRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbRoles` (
  `idRole` VARCHAR(8) NOT NULL,
  `roleName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centrosacad`.`tbUsuariosRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbUsuariosRoles` (
  `nombreUsuario` VARCHAR(8) NOT NULL,
  `idRole` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`nombreUsuario`, `idRole`),
  INDEX `fk_tbUsuarios_has_tbRoles_tbRoles1_idx` (`idRole` ASC) VISIBLE,
  INDEX `fk_tbUsuarios_has_tbRoles_tbUsuarios_idx` (`nombreUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tbUsuarios_has_tbRoles_tbUsuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `centrosacad`.`tbUsuarios` (`nombreUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbUsuarios_has_tbRoles_tbRoles1`
    FOREIGN KEY (`idRole`)
    REFERENCES `centrosacad`.`tbRoles` (`idRole`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
